languages:
  automatically: Automatically
  c: C
  cpp: C++
  cs: C#
  clojure: Clojure
  coffeescript: CoffeeScript
  crystal: Crystal
  css: CSS
  bash: Bash
  d: D
  dart: Dart
  django: Django
  dockerfile: Dockerfile
  elm: Elm
  erlang: Erlang
  fortran: Fortran
  go: Go
  groovy: Groovy
  haml: HAML
  handlebars: Handlebars
  haskell: Haskell
  html: HTML
  http: HTTP
  java: Java
  javascript: JavaScript
  julia: Julia
  stex: LaTeX
  less: LESS
  livescript: Livescript
  lua: Lua
  markdown: Markdown
  nginx: Nginx
  objectivec: Objective-C
  octave: Octave/Matlab
  perl: Perl
  php: PHP
  powershell: Powershell
  plain: Plain Text
  puppet: Puppet
  python: Python
  r: R
  ruby: Ruby
  rust: Rust
  scss: SCSS
  stylus: Stylus
  smalltalk: Smalltalk
  sql: SQL
  stylus: Stylus
  swift: Swift
  tcl: Tcl
  toml: TOML
  twig: Twig
  xml: XML
  xquery: XQuery
  yaml: YAML
